import type { Meta, StoryObj } from "@storybook/react";
import Component from "./View";

const meta: Meta<typeof Component> = {
  title: "widgets/TopReferralTable",
  component: Component,
  tags: ["autodocs"],
  parameters: {
    layout: "fullscreen",
  },
};

export default meta;
type Story = StoryObj<typeof Component>;

export const Default: Story = {
  args: {
    data: [
      ["kr", "seoul", "guro-gu", "119"],
      ["kr", "north chungcheong", "cheongju-si", "14"],
      ["kr", "gyeonggi-do", "gwangmyeong-si", "52"],
      ["kr", "seoul", "mapo-gu", "36"],
      ["kr", "gyeongsangnam-do", "gimhae", "52"],
      ["in", "karnataka", "bengaluru", "9"],
      ["kr", "ulsan", "ulsan", "14"],
      ["vn", "tinh quang nam", "thuan an", "1"],
      ["kr", "gyeonggi-do", "anyang-si", "52"],
      ["kr", "gyeonggi-do", "hanam", "21"],
      ["kr", "gyeonggi-do", "pyeongtaek-si", "9"],
      ["kr", "gangwon-do", "chuncheon", "6"],
      ["kr", "north chungcheong", "chungju", "4"],
      ["", "", "", "22"],
      ["us", "virginia", "ashburn", "21"],
      ["kr", "gyeongsangbuk-do", "pohang", "7"],
      ["kr", "chungcheongnam-do", "asan", "6"],
      ["kr", "sejong-si", "sejong", "8"],
      ["be", "flemish brabant province", "heverlee", "4"],
      ["de", "north rhine-westphalia", "rietberg", "1"],
      ["tw", "", "", "1"],
      ["us", "ohio", "sylvania", "1"],
      ["id", "", "", "1"],
      ["us", "california", "granada hills", "1"],
      ["ua", "", "", "2"],
      ["jp", "tokyo", "shinagawa", "1"],
      ["kr", "seoul", "nowon-gu", "40"],
      ["kr", "gyeonggi-do", "ansan-si", "28"],
      ["kr", "jeollabuk-do", "gunsan", "2"],
      ["kr", "daegu", "daegu", "54"],
      ["kr", "daejeon", "daejeon", "29"],
      ["kr", "seoul", "dongdaemun-gu", "113"],
      ["kr", "seoul", "jungnang-gu", "28"],
      ["kr", "gyeonggi-do", "anseong", "5"],
      ["vn", "ho chi minh", "ho chi minh city", "20"],
      ["kr", "gyeonggi-do", "namyangju", "25"],
      ["ae", "dubai", "dubai", "2"],
      ["kr", "chungcheongnam-do", "gongju", "1"],
      ["ie", "leinster", "dublin", "10"],
      ["us", "california", "los angeles", "2"],
      ["kr", "seoul", "eunpyeong-gu", "23"],
      ["kr", "gyeongsangnam-do", "yangsan", "3"],
      ["ca", "", "", "2"],
      ["kr", "gyeongsangbuk-do", "gumi", "3"],
      ["kr", "gyeonggi-do", "icheon-si", "3"],
      ["kr", "seoul", "seocho", "1"],
      ["kr", "gyeonggi-do", "yangju", "5"],
      ["kr", "jeollanam-do", "yeosu", "2"],
      ["ca", "ontario", "toronto", "1"],
      ["us", "massachusetts", "boston", "1"],
      ["vn", "long an", "tan an", "1"],
      ["jp", "tokyo", "tokyo", "13021"],
      ["gb", "", "", "3"],
      ["kr", "seoul", "seodaemun-gu", "24"],
      ["kr", "seoul", "yeongdeungpo-dong", "100"],
      ["kr", "gyeonggi-do", "hwaseong-si", "44"],
      ["kr", "gyeonggi-do", "pocheon-si", "4"],
      ["kr", "seoul", "yangcheon-gu", "75"],
      ["kr", "gyeonggi-do", "gimpo-si", "33"],
      ["kr", "gyeonggi-do", "paju", "22"],
      ["kr", "gyeonggi-do", "uijeongbu-si", "20"],
      ["ca", "quebec", "chicoutimi", "1"],
      ["kr", "gyeongsangnam-do", "tongyeong-si", "3"],
      ["kr", "chungcheongnam-do", "yesan", "1"],
      ["tw", "taipei city", "taipei", "8"],
      ["se", "", "", "1"],
      ["tw", "taichung city", "taichung", "1"],
      ["in", "haryana", "faridabad", "2"],
      ["us", "florida", "miami", "3"],
      ["ca", "quebec", "mont-saint-hilaire", "1"],
      ["kr", "north chungcheong", "jincheon-gun", "5"],
      ["us", "illinois", "chicago", "1"],
      ["jp", "tokyo", "taito", "1"],
      ["us", "california", "walnut", "1"],
      ["id", "banten", "tangerang", "1"],
      ["br", "sao paulo", "sorocaba", "1"],
      ["kr", "gangwon-do", "inje", "1"],
      ["us", "virginia", "", "2"],
      ["us", "hawaii", "honolulu", "1"],
      ["kr", "gangwon-do", "sokcho", "2"],
      ["cn", "shanghai", "shanghai", "1"],
      ["cn", "ningsia hui autonomous region", "yinchuan", "1"],
      ["es", "madrid", "madrid", "1"],
      ["be", "flemish brabant province", "leuven", "1"],
      ["au", "western australia", "perth", "1"],
    ],
  },
};
